app/lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug(Ueberauth)
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api", AppWeb do
    pipe_through(:api)
    post("/preview", Api.PreviewController, :create)
  end

  scope "/auth", AppWeb do
    pipe_through(:browser)

    get("/:provider", AuthorisationController, :request)
    get("/:provider/callback", AuthorisationController, :callback)
  end

  scope "/", AppWeb do
    pipe_through(:browser)
    pipe_through(AppWeb.CurrentUserPipeline)

    scope "/current_user" do
      get("/", CurrentUserController, :show)
    end

    scope "/projects" do
      resources("/", ProjectController, only: [:show, :create]) do
        put("/provider_connection", ProjectController, :create_provider_connection)
      end
    end
  end

  scope "/", AppWeb do
    pipe_through(:browser)
    get("/", ApplicationController, :index)
    get("/preview", PreviewController, :show)
    get("/healthcheck", ApplicationController, :healthcheck)
  end
end

app/lib/app_web/controllers/current_user_controller.ex
defmodule AppWeb.CurrentUserController do
  alias App.{Roles, Repo, Projects}
  import Ecto.Query, only: [from: 2]
  use AppWeb, :controller

  def show(conn, _params) do
    current_user = Guardian.Plug.current_resource(conn)

    new_project = Projects.Project.changeset(%Projects.Project{})

    roles =
      from(role in Roles.Role,
        where: role.user_id == type(^current_user.id, :binary_id),
        preload: [:project]
      )
      |> Repo.all()

    conn
    |> assign(:current_user, current_user)
    |> assign(:new_project, new_project)
    |> assign(:roles, roles)
    |> render("show.html", conn: conn)
  end
end

app/lib/app_web/views/current_user_view.ex
defmodule AppWeb.CurrentUserView do
  use AppWeb, :view
end

app/lib/app_web/templates/current_user/show.html.eex
<div class="container">
  <div class="content">
    <h1>Current User</h1>
    <h2>Roles</h2>
    <p>These are the roles that you currently have at your projects.</p>

    <%= if length(@roles) == 0 do %>
      <p>
        <strong>You have no roles at any projects.</strong>
      </p>
    <% else %>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Role</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= Enum.map @roles, fn(role) -> %>
            <tr>
              <td>
                <%= link(role.project.name, to: project_path(@conn, :show, role.project)) %>
              </td>
              <td>Admin</td>
              <td>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <h2>Create new project</h2>
    <p>You will be created as an admin of the new project</p>
    <%= form_for @new_project, project_path(@conn, :create), fn f -> %>

      <div class="field">
        <label class="label">
          Name
        </label>
        <div class="control">
          <%= text_input f, :name, class: "input" %>
        </div>
      </div>

      <%= submit "Submit" %>
    <% end %>
  </div>
</div>